### ISSUE TITLE
v3.0.8 版本的 login url 有问题啊

### ISSUE THREAD

**Issue by Vastxiao** [qingqingxuan/arco-work#12]
![image](https://github.com/user-attachments/assets/bf04183b-1c48-47ce-be6c-7d0b5d09defe)

![image](https://github.com/user-attachments/assets/eec08bea-b719-4a36-a290-2e554dbee0da)

v3.0.8 版本的 login url 有问题啊

**Comment by Vastxiao** [comment]
vite-plugin-api-serve 的问题

**Comment by qingqingxuan** [comment]
> vite-plugin-api-serve 的问题

可否具体说说什么问题？

**Comment by Vastxiao** [comment]
vite-plugin-api-serve 看你这个插件开发是用来代替mock模拟后端数据的
在插件 api.config.ts 配置 /login 模拟响应后
那么在插件启用后，url  /login 在浏览器输入请求会优先被插件拦截，处理的是后端的响应的而不是被vue内部路由处理
把 api.config.ts 删除后，在vite-plugin-api-serve启动时，会默认产生一个文件，mock数据是错误的
  所以被浏览器处理后的结果就是上面的报错，而不是跳转到登录页。

所以你这个 api.config.ts  插件使用的话，建议能够支持下添加后端地址参数，比如：
import apiServe from 'vite-plugin-api-serve';

export default defineConfig({
  plugins: [
    vue(),
    apiServe({
      port: 3001, // 指定端口
      hostname: '0.0.0.0', // 地址
    }),
  ],
});
以此来规避后端和前端url地址冲突的问题

额外看了vite-plugin-api-serve这个readme，不知道是否能支持模拟向应http的状态码，比如403,401,502这种
还有就是api.config.ts 可以拆到目录里多文件会好点
有实现的话，插件应该会挺好用的

**Comment by qingqingxuan** [comment]
在使用的时候serve插件的时候可以配置 prefix 属性，这样对于非remote的请求，就会把 prefix 和 url 合并成完整的请求路径，如：/api/login。对于http的状态码完全可以在请求处理中可以根据自己的实际需要自定义状态码。

**Comment by qingqingxuan** [comment]
> vite-plugin-api-serve 看你这个插件开发是用来代替mock模拟后端数据的 在插件 api.config.ts 配置 /login 模拟响应后 那么在插件启用后，url /login 在浏览器输入请求会优先被插件拦截，处理的是后端的响应的而不是被vue内部路由处理 把 api.config.ts 删除后，在vite-plugin-api-serve启动时，会默认产生一个文件，mock数据是错误的 所以被浏览器处理后的结果就是上面的报错，而不是跳转到登录页。
> 
> 所以你这个 api.config.ts 插件使用的话，建议能够支持下添加后端地址参数，比如： import apiServe from 'vite-plugin-api-serve';
> 
> export default defineConfig({ plugins: [ vue(), apiServe({ port: 3001, // 指定端口 hostname: '0.0.0.0', // 地址 }), ], }); 以此来规避后端和前端url地址冲突的问题
> 
> 额外看了vite-plugin-api-serve这个readme，不知道是否能支持模拟向应http的状态码，比如403,401,502这种 还有就是api.config.ts 可以拆到目录里多文件会好点 有实现的话，插件应该会挺好用的

在使用的时候serve插件的时候可以配置 prefix 属性，这样对于非remote的请求，就会把 prefix 和 url 合并成完整的请求路径，如：/api/login。对于http的状态码完全可以在请求处理中可以根据自己的实际需要自定义状态码。
